#!/bin/sh
set -xe
HOST=gate.lan
DST=$HOST:wirikiki-posix

DIST=1 make jsfiles
rsync -rav apps $DST/
scp -r wirikiki $DST/
ssh -- $HOST sudo systemctl restart wirikiki
ssh -- $HOST sudo nginx -s reload
