[token]
algorithm = "HS256"
key = "kHi37vNk93Dd1LgieCGk+d1axrrQYJ6bM4OEqtu78HA="
# in minutes: 10 days
expire_minutes = 1440

[database]
directory = "./myKB"
# TODO: add: git to replace "USE_GIT"

[users]
anonymous = "anonymous"
fab = "pass"
john = "123"
